app.database.host=${DB_HOST:localhost}
app.database.port=${POSTGRES_PORT:5432}
app.database.name=${POSTGRES_DB:}
app.database.username=${POSTGRES_USER:}
app.database.password=${POSTGRES_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo
