spring.application.name=gestao-acoes-corretoras
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
spring.profiles.group.local=dev

app.time-zone=America/Sao_Paulo
spring.jackson.time-zone=America/Sao_Paulo

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}
app.http.connect-timeout=${APP_HTTP_CONNECT_TIMEOUT:3s}
app.http.read-timeout=${APP_HTTP_READ_TIMEOUT:5s}

app.integrations.brasil-api.base-url=${BRASIL_API_BASE_URL:https://brasilapi.com.br/api}
app.integrations.via-cep.base-url=${VIA_CEP_BASE_URL:https://viacep.com.br/ws}
app.integrations.cvm.base-url=${CVM_BASE_URL:https://dados.cvm.gov.br}
app.integrations.brapi.base-url=${BRAPI_BASE_URL:https://brapi.dev/api}
app.integrations.brapi.token=${BRAPI_TOKEN:}
app.integrations.twelve-data.base-url=${TWELVE_DATA_BASE_URL:https://api.twelvedata.com}
app.integrations.twelve-data.api-key=${TWELVE_DATA_API_KEY:}
app.integrations.awesome-api.base-url=${AWESOME_API_BASE_URL:https://economia.awesomeapi.com.br}
