ALTER TABLE asset ADD COLUMN asset_type VARCHAR(20) DEFAULT 'STOCK' NOT NULL;
ALTER TABLE asset ADD COLUMN status VARCHAR(16) DEFAULT 'ACTIVE' NOT NULL;
ALTER TABLE quote ADD COLUMN source VARCHAR(60) DEFAULT 'LEGACY' NOT NULL;
ALTER TABLE exchange_rate ADD COLUMN source VARCHAR(60) DEFAULT 'LEGACY' NOT NULL;

ALTER TABLE asset ADD CONSTRAINT ck_asset_type CHECK (asset_type IN ('STOCK'));
ALTER TABLE asset ADD CONSTRAINT ck_asset_status CHECK (status IN ('ACTIVE', 'INACTIVE'));
