import '@testing-library/jest-dom/vitest'
import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { AuthContext } from '../context/auth-context.js'
import { AccountApiError, changeEmail, changePassword, deleteAccount, getCurrentAccount } from '../api/accounts.js'
import AccountPage from './AccountPage.jsx'
vi.mock('../api/accounts.js', async original=>({...await original(),changeEmail:vi.fn(),changePassword:vi.fn(),deleteAccount:vi.fn(),getCurrentAccount:vi.fn()}))
afterEach(()=>{cleanup();vi.clearAllMocks()})
const account={name:'Ana Silva',cpf:'529.***.***-25',email:'a***@example.com'}
function setup(overrides={}){const value={account,clear:vi.fn(),refresh:vi.fn().mockResolvedValue(true),...overrides};render(<AuthContext.Provider value={value}><MemoryRouter initialEntries={['/app/conta']}><Routes><Route path="/app/conta" element={<AccountPage/>}/><Route path="/login" element={<div>Login destino</div>}/></Routes></MemoryRouter></AuthContext.Provider>);return value}
describe('AccountPage',()=>{
  it('exibe dados mascarados e marca os sete campos como obrigatórios',()=>{setup();expect(screen.getByText('529.***.***-25')).toBeInTheDocument();expect(screen.getByText('a***@example.com')).toBeInTheDocument();expect(screen.queryByDisplayValue('Ana Silva')).not.toBeInTheDocument();expect(screen.getAllByText('obrigatório')).toHaveLength(7);expect(document.querySelectorAll('input[required]')).toHaveLength(7)})
  it('altera e-mail, limpa auth e redireciona para login',async()=>{changeEmail.mockResolvedValue();const auth=setup();fireEvent.change(screen.getByLabelText(/Novo e-mail/),{target:{value:'novo@example.com'}});fireEvent.change(screen.getAllByLabelText(/Senha atual/)[0],{target:{value:'Atual@123'}});fireEvent.click(screen.getAllByRole('button',{name:'Salvar alteração'})[0]);expect(await screen.findByText('Login destino')).toBeInTheDocument();expect(changeEmail).toHaveBeenCalledWith({newEmail:'novo@example.com',currentPassword:'Atual@123'});expect(auth.clear).toHaveBeenCalled()})
  it('mantém erros de senha isolados e acessíveis quando sessão continua válida',async()=>{changePassword.mockRejectedValue(new AccountApiError('Dados inválidos.',{currentPassword:['Senha atual incorreta.'],newPassword:['Senha deve conter número.']},401));getCurrentAccount.mockResolvedValue(account);setup();fireEvent.click(screen.getAllByRole('button',{name:'Salvar alteração'})[1]);expect(await screen.findByText('Senha deve conter número.')).toBeInTheDocument();expect(screen.getByLabelText(/Nova senha/)).toHaveAttribute('aria-invalid','true');expect(screen.getByLabelText(/Novo e-mail/)).toHaveAttribute('aria-invalid','false');expect(screen.getAllByText('Senha atual incorreta.')).toHaveLength(1)})
  it('redireciona somente quando /me confirma sessão expirada',async()=>{changeEmail.mockRejectedValue(new AccountApiError('Sessão inválida.',{},401));getCurrentAccount.mockRejectedValue(new AccountApiError('Sessão inválida.',{},401));const auth=setup();fireEvent.click(screen.getAllByRole('button',{name:'Salvar alteração'})[0]);expect(await screen.findByText('Login destino')).toBeInTheDocument();expect(auth.clear).toHaveBeenCalled()})
  it('preserva a página e oferece retry se a validação da sessão falha tecnicamente',async()=>{changeEmail.mockRejectedValue(new AccountApiError('Não autorizado.',{},401));getCurrentAccount.mockRejectedValueOnce(new AccountApiError('Servidor indisponível.',{},500)).mockResolvedValueOnce(account);setup();fireEvent.click(screen.getAllByRole('button',{name:'Salvar alteração'})[0]);expect(await screen.findByText('Servidor indisponível.')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Tentar novamente'}));expect(await screen.findByRole('alert')).toHaveTextContent('Não autorizado.')})
  it('altera senha e bloqueia duplo envio por formulário',async()=>{let resolve;changePassword.mockReturnValue(new Promise(r=>{resolve=r}));setup();const buttons=screen.getAllByRole('button',{name:'Salvar alteração'});fireEvent.click(buttons[1]);fireEvent.click(buttons[1]);expect(changePassword).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Salvando…'})).toBeDisabled();resolve();expect(await screen.findByText('Login destino')).toBeInTheDocument()})
  it('bloqueia duplo envio também no formulário de e-mail',()=>{changeEmail.mockReturnValue(new Promise(()=>{}));setup();const button=screen.getAllByRole('button',{name:'Salvar alteração'})[0];fireEvent.click(button);fireEvent.click(button);expect(changeEmail).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Salvando…'})).toBeDisabled()})
  it('exige os três campos de exclusão antes de chamar a API',async()=>{setup();fireEvent.click(screen.getByRole('button',{name:'Excluir minha conta'}));expect(await screen.findByText('E-mail atual é obrigatório.')).toBeInTheDocument();expect(screen.getByText('Senha atual é obrigatória.')).toBeInTheDocument();expect(screen.getByText('Digite Excluir para confirmar.')).toBeInTheDocument();expect(deleteAccount).not.toHaveBeenCalled()})
  it('impede exclusão quando a confirmação não é exatamente Excluir',async()=>{setup();fireEvent.change(screen.getByLabelText(/E-mail atual/),{target:{value:'ana@example.com'}});fireEvent.change(screen.getByLabelText(/Senha atual/,{selector:'#deletePassword'}),{target:{value:'Senha@123'}});fireEvent.change(screen.getByLabelText(/Digite Excluir/),{target:{value:'excluir'}});fireEvent.click(screen.getByRole('button',{name:'Excluir minha conta'}));expect(await screen.findByText('A confirmação deve ser exatamente Excluir.')).toBeInTheDocument();expect(deleteAccount).not.toHaveBeenCalled();expect(screen.getByLabelText(/Digite Excluir/)).toHaveValue('excluir')})
  it('exclui, limpa a autenticação e redireciona para o login',async()=>{deleteAccount.mockResolvedValue();const auth=setup();fireEvent.change(screen.getByLabelText(/E-mail atual/),{target:{value:'ana@example.com'}});fireEvent.change(screen.getByLabelText(/Senha atual/,{selector:'#deletePassword'}),{target:{value:'Senha@123'}});fireEvent.change(screen.getByLabelText(/Digite Excluir/),{target:{value:'Excluir'}});fireEvent.click(screen.getByRole('button',{name:'Excluir minha conta'}));expect(await screen.findByText('Login destino')).toBeInTheDocument();expect(deleteAccount).toHaveBeenCalledWith({email:'ana@example.com',password:'Senha@123',confirmation:'Excluir'});expect(auth.clear).toHaveBeenCalled()})
  it('preserva os dados e apresenta erros funcionais da exclusão',async()=>{deleteAccount.mockRejectedValue(new AccountApiError('Confirmação inválida.',{password:['Senha atual incorreta.'],confirmation:['Confirmação inválida.']},400));setup();fireEvent.change(screen.getByLabelText(/E-mail atual/),{target:{value:'ana@example.com'}});fireEvent.change(screen.getByLabelText(/Senha atual/,{selector:'#deletePassword'}),{target:{value:'Senha@123'}});fireEvent.change(screen.getByLabelText(/Digite Excluir/),{target:{value:'Excluir'}});fireEvent.click(screen.getByRole('button',{name:'Excluir minha conta'}));expect(await screen.findByRole('alert')).toHaveTextContent('Confirmação inválida.');expect(screen.getByText('Senha atual incorreta.')).toBeInTheDocument();expect(screen.getByLabelText(/E-mail atual/)).toHaveValue('ana@example.com');expect(screen.getByLabelText(/Digite Excluir/)).toHaveValue('Excluir')})
  it('bloqueia múltiplas exclusões enquanto a solicitação está pendente',()=>{deleteAccount.mockReturnValue(new Promise(()=>{}));setup();fireEvent.change(screen.getByLabelText(/E-mail atual/),{target:{value:'ana@example.com'}});fireEvent.change(screen.getByLabelText(/Senha atual/,{selector:'#deletePassword'}),{target:{value:'Senha@123'}});fireEvent.change(screen.getByLabelText(/Digite Excluir/),{target:{value:'Excluir'}});const button=screen.getByRole('button',{name:'Excluir minha conta'});fireEvent.click(button);fireEvent.click(button);expect(deleteAccount).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Excluindo conta…'})).toBeDisabled()})
  it('limpa dados privados quando a sessão expira durante a exclusão',async()=>{deleteAccount.mockRejectedValue(new AccountApiError('Sessão inválida.',{},401));getCurrentAccount.mockRejectedValue(new AccountApiError('Sessão inválida.',{},401));const auth=setup();fireEvent.change(screen.getByLabelText(/E-mail atual/),{target:{value:'ana@example.com'}});fireEvent.change(screen.getByLabelText(/Senha atual/,{selector:'#deletePassword'}),{target:{value:'Senha@123'}});fireEvent.change(screen.getByLabelText(/Digite Excluir/),{target:{value:'Excluir'}});fireEvent.click(screen.getByRole('button',{name:'Excluir minha conta'}));expect(await screen.findByText('Login destino')).toBeInTheDocument();expect(auth.clear).toHaveBeenCalled()})
})
