import '@testing-library/jest-dom/vitest'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { associateBroker, BrokerApiError, getActiveBrokers, removeBroker, searchBroker } from '../api/brokers.js'
import { AuthContext } from '../context/auth-context.js'
import BrokersPage from './BrokersPage.jsx'

vi.mock('../api/brokers.js', async (load) => ({ ...await load(), associateBroker: vi.fn(), getActiveBrokers: vi.fn(), removeBroker: vi.fn(), searchBroker: vi.fn() }))
const broker = { associationId: 'association-1', cnpj: '12345678000190', corporateName: 'Corretora Exemplo S.A.', tradeName: 'Exemplo', registrationStatus: 'ATIVA', cvmCategory: 'CTVM', postalCode: '01001000', street: 'Praça da Sé', complement: null, district: 'Sé', city: 'São Paulo', state: 'SP' }
const preview = { ...broker }
delete preview.associationId
afterEach(cleanup)

function setup(auth = { clear: vi.fn() }) {
  render(<AuthContext.Provider value={auth}><MemoryRouter initialEntries={['/app/corretoras']}><Routes><Route path="/app/corretoras" element={<BrokersPage />} /><Route path="/login" element={<p>Login destino</p>} /></Routes></MemoryRouter></AuthContext.Provider>)
  return auth
}
async function ready(items = [broker]) { getActiveBrokers.mockResolvedValue(items); setup(); await screen.findByRole('heading', { name: 'Minhas corretoras' }) }
async function searchValid() { fireEvent.change(screen.getByLabelText('CNPJ'), { target: { value: broker.cnpj } }); fireEvent.click(screen.getByRole('button', { name: 'Pesquisar' })); await screen.findByRole('heading', { name: 'Confira antes de associar' }) }

describe('BrokersPage', () => {
  beforeEach(() => vi.clearAllMocks())
  it('mostra carregamento e depois a lista oficial', async () => { let resolve; getActiveBrokers.mockReturnValue(new Promise((done) => { resolve = done })); setup(); expect(screen.getByRole('status')).toHaveTextContent('Carregando corretoras'); resolve([broker]); expect(await screen.findByText('Corretora Exemplo S.A.')).toBeInTheDocument() })
  it('mostra estado vazio', async () => { await ready([]); expect(screen.getByText('Nenhuma corretora associada')).toBeInTheDocument() })
  it('permite tentar novamente após erro inicial', async () => { getActiveBrokers.mockRejectedValueOnce(new BrokerApiError('Servidor indisponível.')).mockResolvedValueOnce([]); setup(); expect(await screen.findByRole('alert')).toHaveTextContent('Servidor indisponível.'); fireEvent.click(screen.getByRole('button', { name: 'Tentar novamente' })); expect(await screen.findByText('Nenhuma corretora associada')).toBeInTheDocument() })
  it('limpa dados e navega ao login quando a sessão expira', async () => { getActiveBrokers.mockRejectedValue(new BrokerApiError('Sessão expirada.', {}, 401)); const auth = setup(); expect(await screen.findByText('Login destino')).toBeInTheDocument(); expect(auth.clear).toHaveBeenCalledOnce(); expect(screen.queryByText('Corretora Exemplo S.A.')).not.toBeInTheDocument() })
  it.each(['', '123', '12.345.678/0001'])('não pesquisa CNPJ estruturalmente inválido: %s', async (value) => { await ready([]); fireEvent.change(screen.getByLabelText('CNPJ'), { target: { value } }); fireEvent.click(screen.getByRole('button', { name: 'Pesquisar' })); expect(screen.getByText('Informe um CNPJ com 14 dígitos.')).toBeInTheDocument(); expect(searchBroker).not.toHaveBeenCalled() })
  it('exibe a prévia consolidada e a invalida ao mudar o CNPJ', async () => { searchBroker.mockResolvedValue(preview); await ready([]); await searchValid(); expect(searchBroker).toHaveBeenCalledWith(broker.cnpj); expect(screen.getByText('Praça da Sé, Sé, São Paulo - SP, 01001000')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('CNPJ'), { target: { value: '12345678000191' } }); expect(screen.queryByRole('heading', { name: 'Confira antes de associar' })).not.toBeInTheDocument() })
  it('ignora a resposta obsoleta se o CNPJ mudar durante a pesquisa', async () => { let finish; searchBroker.mockReturnValue(new Promise((resolve) => { finish = resolve })); await ready([]); fireEvent.change(screen.getByLabelText('CNPJ'), { target: { value: broker.cnpj } }); fireEvent.click(screen.getByRole('button', { name: 'Pesquisar' })); fireEvent.change(screen.getByLabelText('CNPJ'), { target: { value: '12345678000191' } }); finish(preview); await waitFor(() => expect(searchBroker).toHaveBeenCalledOnce()); expect(screen.queryByRole('heading', { name: 'Confira antes de associar' })).not.toBeInTheDocument() })
  it('preserva a lista quando a pesquisa falha', async () => { searchBroker.mockRejectedValue(new BrokerApiError('Fonte externa indisponível.')); await ready(); fireEvent.change(screen.getByLabelText('CNPJ'), { target: { value: broker.cnpj } }); fireEvent.click(screen.getByRole('button', { name: 'Pesquisar' })); expect(await screen.findByRole('alert')).toHaveTextContent('Fonte externa indisponível.'); expect(screen.getByText('Corretora Exemplo S.A.')).toBeInTheDocument() })
  it('associa uma vez e recarrega somente a lista oficial', async () => { searchBroker.mockResolvedValue(preview); associateBroker.mockResolvedValue(broker); getActiveBrokers.mockResolvedValueOnce([]).mockResolvedValueOnce([broker]); setup(); await screen.findByText('Nenhuma corretora associada'); await searchValid(); const button = screen.getByRole('button', { name: 'Associar corretora' }); fireEvent.click(button); fireEvent.click(button); await screen.findByText('Corretora associada. A lista foi atualizada.'); expect(associateBroker).toHaveBeenCalledOnce(); expect(getActiveBrokers).toHaveBeenCalledTimes(2); expect(screen.getByText('Corretora Exemplo S.A.')).toBeInTheDocument() })
  it('preserva a prévia em duplicidade', async () => { searchBroker.mockResolvedValue(preview); associateBroker.mockRejectedValue(new BrokerApiError('Corretora já associada.', {}, 409)); await ready([]); await searchValid(); fireEvent.click(screen.getByRole('button', { name: 'Associar corretora' })); expect(await screen.findByRole('alert')).toHaveTextContent('Corretora já associada.'); expect(screen.getByRole('heading', { name: 'Confira antes de associar' })).toBeInTheDocument() })
  it('mantém a corretora e mostra erro quando remoção é bloqueada', async () => { removeBroker.mockRejectedValue(new BrokerApiError('Existem posições vinculadas.', {}, 409)); await ready(); fireEvent.click(screen.getByRole('button', { name: 'Remover corretora' })); const card = screen.getByText('Corretora Exemplo S.A.').closest('article'); expect(await within(card).findByRole('alert')).toHaveTextContent('Existem posições vinculadas.'); expect(screen.getByText('Corretora Exemplo S.A.')).toBeInTheDocument(); expect(getActiveBrokers).toHaveBeenCalledOnce() })
  it('remove uma vez e substitui a lista pela resposta oficial', async () => { let finish; removeBroker.mockReturnValue(new Promise((resolve) => { finish = resolve })); getActiveBrokers.mockResolvedValueOnce([broker]).mockResolvedValueOnce([]); setup(); await screen.findByText('Corretora Exemplo S.A.'); const button = screen.getByRole('button', { name: 'Remover corretora' }); fireEvent.click(button); fireEvent.click(button); expect(removeBroker).toHaveBeenCalledOnce(); expect(screen.getByText('Corretora Exemplo S.A.')).toBeInTheDocument(); finish(); expect(await screen.findByText('Nenhuma corretora associada')).toBeInTheDocument(); expect(getActiveBrokers).toHaveBeenCalledTimes(2) })
  it('serializa remoções de corretoras diferentes enquanto há operação pendente', async () => { const second = { ...broker, associationId: 'association-2', cnpj: '98765432000110', corporateName: 'Outra Corretora S.A.' }; removeBroker.mockReturnValue(new Promise(() => {})); await ready([broker, second]); const buttons = screen.getAllByRole('button', { name: 'Remover corretora' }); fireEvent.click(buttons[0]); fireEvent.click(buttons[1]); expect(removeBroker).toHaveBeenCalledOnce(); expect(buttons[1]).toBeDisabled() })
  it('usa cartões responsivos em vez de tabela larga', async () => { Object.defineProperty(window, 'innerWidth', { configurable: true, value: 375 }); await ready(); expect(document.querySelector('.broker-grid')).toBeInTheDocument(); expect(screen.queryByRole('table')).not.toBeInTheDocument(); await waitFor(() => expect(screen.getByRole('button', { name: 'Remover corretora' })).toBeVisible()) })
})
